### ISSUE TITLE
An error in continue calculate after get equal.

### ISSUE THREAD

**Issue by mrxf** [MichaelMammoliti/calculator.js#1]
Hello,when I have done a caculate,like 9 + 3 =,and get the result.if I want continue caculate like 8 + 3 ,and get a error.Means I have to touch clear after a caculate.But common caculater not like this.

And if you don't mind , I wanna have a discussion with  _define a variable_ .What's the deffience between define a variable equal undefine(this.prevKey = undefined;) and haven't defined a variable?

**Comment by MichaelMammoliti** [comment]
there is no difference declaring a variable doing `var x = undefined;` or `var x;`.

Are you sure? For me it's working.. try it here: http://codepen.io/MichaelMammoliti/pen/waVarr

**Comment by mrxf** [comment]
Thank you.Maybe it was my wrong operation.
